---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "Correlations Quiz 1"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)
```

```{r script-console, echo=FALSE}
question("What is the difference between pairwise deletion and listwise deletion`?",
         answer("Listwise deletion (aka 'complete') is when all missing data are removed. Pariwise deletion is when we use all available data per each pair of variables", correct = TRUE),
         answer("Pairwise deletion (aka 'complete') is when all missing data are removed. Listwise deletion is when we use all available data per each pair of variables"),
         answer("Listwise deletion is when we only remove data from a predefined list. Pairwise deletion is when we remove data from only 2 variables"),
         allow_retry = TRUE,
         random_answer_order = TRUE)
```

<div data-iframe-height></div>