---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "bootstrapped ci"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)

```

```{css, echo=FALSE}
p {
  font-size: 16.5px;
  font-family: "Merriweather", sans-serif;
}

h5 {
  font-size: 16.5px;
  font-family: "Lato", sans-serif;
}

```

```{r prepare, warning=FALSE, message=FALSE}
set.seed(1234)
pop_data <- rnorm(n = 10000, mean = 100, sd = 25)
pop_data <- data.frame(PopulationMeans = pop_data)

sample_data <- data.frame(SampleMeans = sample(pop_data$PopulationMeans, size = 30, replace = FALSE))

library(ggplot2)
```


```{r ex1, exercise = TRUE, exercise.setup = "prepare"}
# Initialize empty vector of diff in means
diffMeans <- NULL


# Begin loop
for (i in 1:100) {
  
  # Draw your sample, get the mean, and get the difference between the mean and 95

  
  # Save (append) the result to `diffMeans`
  
  
}



## DO NOT MODIFY THE CODE BELOW! ##
# If your code works, then the code below should work and you will see the distributions of your diff in means and their confidence intervals.
# NOTE THE `geom_vline` lines of code!

differences <- data.frame(diffMeans)

ggplot() +
  geom_histogram(data = differences, aes(x = diffMeans), binwidth = 1) +
  theme_classic() +
  xlab("Differences in Means") +
  ylab("Count") +
  geom_vline(aes(xintercept = quantile(diffMeans, probs = .025), color = "Lower 2.5%"), size = 2) +
  geom_vline(aes(xintercept = quantile(diffMeans, probs = .975), color = "Upper 2.5%"), size = 2) +
  ggtitle("Bootstrapped Confidence Intervals")
```


```{r ex1-solution}

# Initialize empty vector of diff in means
diffMeans <- NULL


# Begin loop
for (i in 1:100) {
  
  # Draw your sample, get the mean, and get the difference between the mean and 95
  indices <- sample(1:30, size = 30, replace = T)
  subsample <- sample_data[indices, 1]
  meanSample <- mean(subsample)
  diff <- meanSample - 95
  
  # Save (append) the result to `diffMeans`
  diffMeans <- append(diffMeans, diff)
  
}



## DO NOT MODIFY THE CODE BELOW! ##
# If your code works, then the code below should work and you will see the distributions of your diff in means and their confidence intervals.
# NOTE THE `geom_vline` lines of code!

differences <- data.frame(diffMeans)
ggplot() +
  geom_histogram(data = differences, aes(x = diffMeans), binwidth = 1) +
  theme_classic() +
  xlab("Differences in Means") +
  ylab("Count") +
  geom_vline(aes(xintercept = quantile(diffMeans, probs = .025), color = "Lower 2.5%"), size = 2) +
  geom_vline(aes(xintercept = quantile(diffMeans, probs = .975), color = "Upper 2.5%"), size = 2) +
  ggtitle("Bootstrapped Confidence Intervals")
```

```{r ex1-check}
grade_code()
```

<div data-iframe-height></div>