---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "t-test"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)

```

```{css, echo=FALSE}
p {
  font-size: 16.5px;
  font-family: "Merriweather", sans-serif;
}

h5 {
  font-size: 16.5px;
  font-family: "Lato", sans-serif;
}

```

```{r prepare-tt, warning=FALSE, message=FALSE}
library(ggplot2)

midus <- read.csv("https://elegant-wilson-496cf4.netlify.app/practice/07-practice/data/midus.csv")

midus$sex <- factor(midus$sex)
midus$heart_self <- factor(midus$heart_self)
midus$heart_father <- factor(midus$heart_father)

midus <- na.omit(midus)

```

```{r ex1, exercise = TRUE, exercise.setup = "prepare-tt"}
# code for t-test (you do NOT need to assign to an object)


# code for boxplot
```

<div id="ex1-hint">
<font size="-1.5">
**Hint:** Check out the relevant slides from 9: Stats & Plot if you're lost.
</font>

<font size="-1.5">
*If you're trying out the BONUS questions, stick to just Running the code -- don't submit it*
</font>
</div>

```{r ex1-solution}
# code for t-test (you do NOT need to assign to an object)
t.test(life_satisfaction ~ heart_self, data = midus)

# code for boxplot
ggplot(data = midus, aes(x = heart_self, y = life_satisfaction)) +
  geom_boxplot()
```

```{r ex1-check}
grade_code()
```

<div data-iframe-height></div>