---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "datviz3"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)

```

```{css, echo=FALSE}
p {
  font-size: 16.5px;
  font-family: "Merriweather", sans-serif;
}

h5 {
  font-size: 16.5px;
  font-family: "Lato", sans-serif;
}

```

```{r prepare-aovsetup, warning=FALSE, message=FALSE}
library(ggplot2)
library(tidyverse)

midus <- read.csv("https://elegant-wilson-496cf4.netlify.app/practice/07-practice/data/midus.csv")

midus$sex <- factor(midus$sex)
midus$heart_self <- factor(midus$heart_self)
midus$heart_father <- factor(midus$heart_father)

midus <- na.omit(midus)

midus$age_category <- cut(x = midus$age,
                          breaks = c(28, 40, 60, 84),
                          labels=c("young", "middle", "old"),
                          include.lowest = TRUE)

session <- c(rep("1", times = 935), rep("2", times = 935))
midus["session"] <- rep(session, times = 2)
midus$session <- as.numeric(midus$session)
midus$session <- factor(midus$session, labels = c("session1", "session2"))

midus$group <- sample(x = c("group1", "group2"), size = 3740,
                  replace = TRUE)
midus$group <- factor(midus$group)

```

```{r ex1, exercise = TRUE, exercise.setup = "prepare-aovsetup", warning=FALSE, message=FALSE}
# Don't modify this code
meansSelfEsteem <- midus %>%
  group_by(age_category) %>%
  summarize(yint = mean(self_esteem))

# Only modify this code
ggplot(data = midus, aes(x = BMI, y = self_esteem)) +
  geom_point(aes(color = age_category)) +
  labs(x = "BMI", y = "Self Esteem",
       title = "Horizontal Mean Lines for Self-Esteem, by Age")
```

<div id="ex1-hint">

<font size="-1.5">
**Hint:** Think about how you do this with vertical lines...
**Hint 2:** You don't need to worry about changing the colors of the lines or changing to dashed lines etc. Just add any lines. 
</font>
</div>

```{r ex1-solution}
# Don't modify this code
meansSelfEsteem <- midus %>%
  group_by(age_category) %>%
  summarize(yint = mean(self_esteem))

# Only modify this code
ggplot(data = midus, aes(x = BMI, y = self_esteem)) +
  geom_point(aes(color = age_category)) +
  labs(x = "BMI", y = "Self Esteem",
       title = "Horizontal Mean Lines for Self-Esteem, by Age") +
  geom_hline(data = meansSelfEsteem,
             aes(yintercept = yint))
```

```{r ex1-check}
grade_code()
```

<div data-iframe-height></div>