---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "practice app 3"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)
library(palmerpenguins)

```

```{css, echo=FALSE}
p {
  font-size: 16.5px;
  font-family: "Merriweather", sans-serif;
}

h5 {
  font-size: 16.5px;
  font-family: "Lato", sans-serif;
}

```

```{r prepare, warning=FALSE, message=FALSE}

iris<-datasets::iris
# Your code goes here
mod_cont <- lm(Petal.Length ~ Sepal.Length + Sepal.Width, data= iris)
  
```

```{r ex1, exercise = TRUE, exercise.setup = "prepare", warning = FALSE, message = FALSE}
# Your code goes here


# Don't delete this line...keep it
summary(mod1)
summary(mod_cont)
```

<div id="ex1-hint">

<font size="-1.5">
$Y \sim X$ 
</font>
</div>


```{r ex1-solution}
# Your code goes here
mod1 <- lm(Petal.Length~Sepal.Length*Sepal.Width,data= iris)

# Don't delete this line...keep it
summary(mod1)
summary(mod_cont)
```

```{r ex1-check}
grade_code()
```

<div data-iframe-height></div>