---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
description: "t-test"
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.eval = FALSE)
knitr::opts_chunk$set(exercise.checker = gradethis::grade_learnr)

```

```{css, echo=FALSE}
p {
  font-size: 16.5px;
  font-family: "Merriweather", sans-serif;
}

h5 {
  font-size: 16.5px;
  font-family: "Lato", sans-serif;
}

```

```{r prepare-su, warning=FALSE, message=FALSE}
midus <- read.csv("https://elegant-wilson-496cf4.netlify.app/practice/07-practice/data/midus.csv")
```

```{r ex1, exercise = TRUE, exercise.setup = "prepare-su"}
# load the ggplot2 package here


# change the 3 variables listed above to factor variables


# get rid of missing variables


# view the first 6 rows; do this with the `head` function
```

<div id="ex1-hint">
<font size="-1.5">
**Hint:** See the end of the 5: Functions practice for more on changing character variables to factor variables.

</font>
</div>

```{r ex1-solution}
# load the ggplot2 package here
library(ggplot2)

# change the 3 variables listed above to factor variables
midus$sex <- factor(midus$sex)
midus$heart_self <- factor(midus$heart_self)
midus$heart_father <- factor(midus$heart_father)

# get rid of missing variables
midus <- na.omit(midus)

# view the first 6 rows; do this with the `head` function
head(midus)
```

```{r ex1-check}
grade_code()
```


<div data-iframe-height></div>